version: '3.1'
services:
  app:
    container_name: app-core
    tty: true # dodane do wyświetlania, z którego kontenera pochodzi informacja w konsoli
    image: tomaszaleksander/simple-clinic:v1.2
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simple_clinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - VERSION=3.0
    networks:
      - spring-boot-postgres
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./build/libs/simple_clinic.jar:/app.jar
  db:
    container_name: db-psql
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=simple_clinic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data_v3
    networks:
      - spring-boot-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-boot-postgres:
    driver: bridge

