server:
  port: 8080
  servlet:
    context-path: /clinic

api:
  cepik:
    url: https://api.cepik.gov.pl/
  petStore:
    url: https://petstore3.swagger.io/api/v3/
  airQuality:
    url: https://api.gios.gov.pl/pjp-api/rest/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/simple_clinic
    username: postgres
    password: postgres
    hikari:
      idle-timeout: 10000
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern=/static/**:
    dispatch:
      trace:
        request: true

  security:
    enabled: true
    csrf:
      enabled: false

  flyway:
    baseline-on-migrate=true:

  doctors:
    descriptions:
      folder: desc/
      prefix: doctorDesc

# Na końcu usuń!!!!
logging:
  level:
    org:
      springframework:
        security: DEBUG
# Do usunięcia przed puszczeniem na produkcję

# api pogodowe
openweathermap:
  apiKey: 54b6d16922202a1681364b76a0112392

